### ISSUE TITLE
counter module

### ISSUE THREAD

**Issue by pkra** [pkra/laml#50]
Counters. We need them.

@scoskey what requirements do you see?

**Comment by scoskey** [comment]
First let me record the amsthm way. Then we should think about whether this is good.

There are chapter, section, and subsection counters. There are also counters for theorem-like environments. Whenever you declare a theorem-like environment, you have an initial choice from 3 options:
1) The environment has no counter and goes unnumbered and un-ref-able
2) The environment joins forces with an existing counter.
3) The environment gets its own new counter.

If you choose (3), you have a choice from 2 options:
A) The counter is numbered alone continuously through the document
B) The counter is numbered "within" another counter, resets when that one increments, and is printed parent.child.

Extra items:
1) One can also choose the "style" of the environment. The options are Theorem, Definition, and Remark. These three style names are stupid and arbitrary. Theorem style has italic contents. Definition style looks "normal". Remark style has italicized name but not content. We should just leave this to CSS.
2) One should also be able to control how the counter is printed by default (as a number or letter). This isn't standard in amsthm but presumably easy to implement.

**Comment by scoskey** [comment]
The amsthm way described above is kind of weird in that it conflates counter names and environment names (by choosing option 3). Maybe it makes more sense for the user to be able to declare named counters, and then specify which environments use which counters.

The default should probably be a "statement" counter which is numbered within a "section" counter, and that's it.

Here is a sample (but would be simpler given we'd have defaults).
````
---
counters:
  - section
    - appearance: roman
  - statement:
    - numberwithin: section
    - appearance: arabic
  - exercise
    - appearance: arabic
statements:
  - theorem:
    - counter: statement
  - definition:
    - counter: statement
  - exercise:
    - counter: exercise
  - question [no counter]
---
````
